config/routes.rb
Fash::Application.routes.draw do
  get "sessions/new"

  get "users/new"

  resources :items

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions









  root :to => 'items#index'


end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :items, :dependent => :destroy

  attr_accessible :email, :password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = current_user.items.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to root_url, notice: 'Item was successfully created.' }
        format.json { render json: root_url, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = current_user.items.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to root_url, notice: 'Item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = current_user.items.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end
	
  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Email or password was invalid"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_for(@item, html: {class: "create-edit"}) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :picture %>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :shop %>
    <%= f.text_field :shop %>
  </div>
  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="form-header">
	<div class="content padding-20">
	<h2>Изменить <%= @item.name %></h2>
</div>
</div>
<div class="content padding-20">
	<%= render 'form' %>
	<img class="item-picture" src="">
</div>

app/views/items/index.html.erb

<div class="content items-list">
  <% if current_user %>
    <%= link_to(new_item_path, class: "add-item") do %>
      <span><strong>+</strong> Add item</span>
    <% end %>
  <% end %>
  <% @items.each do |item| %>
    <div class="item">
      <%= link_to(item, class: "link") do %>
        <span class="image-wrapper">
          <%= image_tag item.picture %>
        </span>
        <div class="info">
          <p class="title"><span><%= item.name %></span></p>
          <strong class="price"><%= item.price %> грн</strong>
        </div>
      <% end %>
      <% if current_user %>
        <div class="edit">
          <%= link_to 'Edit', edit_item_path(item) %>
          <%= link_to 'Destroy', item, confirm: 'Are you sure?', method: :delete %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/items/new.html.erb
<div class="form-header">
	<div class="content padding-20">
	<h2>Добавить</h2>
</div>
</div>
<div class="content padding-20">
	<%= render 'form' %>
	<img class="item-picture" src="">
</div>

app/views/items/show.html.erb
<div class="content item-current padding-20">
	<p id="notice"><%= notice %></p>
	<%= image_tag @item.picture, class: "item-image" %>
	<p class="price"><%= @item.price %> грн</p>
	<p class="name"><%= @item.name %></p>
	<p class="shop">из <%= link_to @item.shop, "http://#{@item.shop}" %></p>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="content">
    <div class="logo">
        <a href="/"><%= image_tag "/assets/logo.png" %></a>
      </div>
    <div class="user">
    <% if current_user %>
      <%= current_user.email %><%= link_to("Log out", logout_path, class: "logout-link") %>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fash</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="wrapper">
	<%= render "layouts/header" %>
	<%= yield %>
</div>

</body>
</html>

app/views/users/new.html.erb
<div class="form-header">
	<div class="content padding-20">
	<h2>Зарегистрироваться</h2>
</div>
</div>
<div class="content padding-20">
<%= form_for(@user, html: {class: "create-edit"}) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>
</div>